{% set name = "opentelemetry-instrumentation-aiohttp-client" %}
{% set version = "0.23b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9cbe812878642c2a091cfd7b1384503e0236db86e6f3c92e3bf9e4b5d5456536

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - aiohttp >=3.0.0,<4.0.0
    - opentelemetry-api =={{ version }}
    - opentelemetry-instrumentation =={{ version }}
    - python >=3.5
    - wrapt >=1.0.0,<2.0.0

test:
  imports:
    - opentelemetry.instrumentation.aiohttp_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-aiohttp-client
  summary: OpenTelemetry aiohttp client instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - twoodwark
    - mariusvniekerk
